### ISSUE TITLE
THE GAME NOT COMPILE

### ISSUE THREAD

**Issue by min89xd** [magnumsrtisswag/MagEngine-Public#11]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ X ] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

source/MagModChart.hx:2: characters 8-16 : Type not found : llua.Lua
source/MagModChart.hx:3: characters 8-17 : Type not found : llua.LuaL
source/MagModChart.hx:4: characters 8-18 : Type not found : llua.State
source/MagModChart.hx:5: characters 8-20 : Type not found : llua.Convert
source/MagModChart.hx:34: characters 20-25 : Type not found : State
source/FreeplayState.hx:20: lines 20-325 : ... Defined in this class
source/PlayState.hx:3250: characters 35-39 : MagModChart has no field call
source/PlayState.hx:3265: characters 17-20 : MagModChart has no field set
source/PlayState.hx:957: characters 18-42 : MagModChart does not have a constructor
source/PlayState.hx:957: characters 18-42 : ... For function argument 'x'
source/PlayState.hx:962: characters 18-42 : MagModChart does not have a constructor
source/PlayState.hx:962: characters 18-42 : ... For function argument 'x'

**Comment by magnumsrtisswag** [comment]
Install the LATEST VERSION of haxe, at the time it is 4.2.4 (https://haxe.org/download/). And Make sure you have both linc_luajit and hxvm-luajit installed. Install them by typing these two commands in command line:
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

If that doesn't work that means you modified the source and therefore I cannot help.
