### ISSUE TITLE
fuck

### ISSUE THREAD

**Issue by Stilic** [magnumsrtisswag/MagEngine-Public#23]
yeah everything i did got erased again bruh
i gonna try to fix that tommorow!

**Comment by magnumsrtisswag** [comment]
well that must be a github issue then, since i did not force push.

**Comment by magnumsrtisswag** [comment]
and it even says 200 commits, bruh

**Comment by Stilic** [comment]
ok

**Comment by Stilic** [comment]
before, how do you commit and push changes to the repo?

**Comment by Stilic** [comment]
> git push origin main --force

remove force shit
