### ISSUE TITLE
hscript

### ISSUE THREAD

**Issue by Manu614** [magnumsrtisswag/MagEngine-Public#26]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?
how to use hscript?

**Comment by magnumsrtisswag** [comment]
just like regular haxe code, but a bit modified. sometimes you won't be able to use ";"
