### ISSUE TITLE
FlxTypedGroup in Hscript doesn't work

### ISSUE THREAD

**Issue by BeansCool54** [magnumsrtisswag/MagEngine-Public#28]
Hi, so I was trying out the engine and noticed FlxTypedGroup stuff don't work. One example is: `
var why:FlxTypedGroup<FlxSprite>;
trace('lol');
why = new FlxTypedGroup<FlxSprite>();
add(why);` but it crashes the game once i open the script

**Comment by magnumsrtisswag** [comment]
hscript cannot recognize colons.

**Comment by magnumsrtisswag** [comment]
np

**Comment by magnumsrtisswag** [comment]
UPDATE: In 1.4.2h I have made some parser changes and it can now parse colons.
